user www-data;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;

    server {
        listen 80 default_server;
        server_name _;

        root /usr/share/cgit;
        index cgit.css;

        location /cgit.css {
            try_files $uri =404;
        }

        location /cgit.png {
            try_files $uri =404;
        }

        location /favicon.ico {
            try_files /cgit.png =404;
        }

        location / {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /usr/lib/cgit/cgit.cgi;
            fastcgi_param PATH_INFO $uri;
            fastcgi_param QUERY_STRING $query_string;
            fastcgi_pass unix:/run/fcgiwrap/fcgiwrap.sock;
            fastcgi_read_timeout 60s;
        }
    }
}
